### PR TITLE
Bug Fix: Add 'toggleShowFileTreeBtn' function in defectCtrl

### LINKED ISSUE #167: [dexter-server] It doesn't work : "Show File Tree" button.
angular.js:9778 ReferenceError: toggleShowFileTreeBtn is not defined
    at h.$scope.loadFileTreeFromDB (defectCtrl.js:261)
    at angular.js:10567
    at angular.js:18627
    at h.$eval (angular.js:12412)
    at h.$apply (angular.js:12510)
    at HTMLButtonElement.<anonymous> (angular.js:18626)
    at HTMLButtonElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.11.1.min.js:3)

### PR DESCRIPTION
**Pull request by Minjung-Baek**
I want to resolve #167

### CODE REVIEW

File: project/dexter-server/public/defect/defectCtrl.js [hunk 1]
```diff
@@ -381,9 +381,13 @@ defectApp.controller('DefectCtrl', function ($scope, $http, $sce, $location, $an
         });
     }
 
-    $scope.toggleShowFileTreeBtn = function(isShowState) {
+    function toggleShowFileTreeBtn(isShowState) {
```
Comment (mdopark) [inline project/dexter-server/public/defect/defectCtrl.js]: What's the difference between befor and after?

Comment (Minjung-Baek) [reply project/dexter-server/public/defect/defectCtrl.js]: There is a bug in the 'defectCtrl.js' [▶ReferenceError: toggleShowFileTreeBtn is not defined]
Because I had changed function 'toggleShowFileTreeBtn' to '$scope.toggleShowFileTreeBtn'.
So I want to mapping it.
